### ISSUE TITLE
Jbender ConstantIntervalGenerator constructor uses nanoseconds not milliseconds

### ISSUE THREAD

**Issue by jamisonhyatt** [circlespainter/comsat-http-client-bench#1]
https://github.com/circlespainter/comsat-http-client-bench/blob/master/clients/src/main/java/co/paralleluniverse/comsat/bench/http/client/ClientBase.java#L65

Just fyi, you should multiply by 1,000,000 before passing into ConstantIntervalGenerator or change the instructions to note they're nanos, not millis.

**Comment by circlespainter** [comment]
Thanks!
